name: volta
description: Elegant charging monitor. Minimal, premium, no RGB.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  battery_plus: ^6.0.2
  flutter_local_notifications: ^17.2.2
  google_fonts: ^6.2.1
  phosphor_flutter: ^2.1.0
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FAFAF7"
  adaptive_icon_foreground: "assets/icon_fg.png"
  min_sdk_android: 24
